#!/bin/bash

# Gmail Configuration Helper
# This script helps configure Gmail SMTP for email notifications

echo "📧 Gmail SMTP Configuration Helper"
echo "=================================="
echo ""
echo "To enable email notifications, you need to configure Gmail SMTP."
echo "Follow these steps:"
echo ""
echo "1. Go to your Google Account settings:"
echo "   https://myaccount.google.com/"
echo ""
echo "2. Navigate to Security → 2-Step Verification"
echo "   (You must have 2FA enabled)"
echo ""
echo "3. Go to Security → App passwords"
echo "   https://myaccount.google.com/apppasswords"
echo ""
echo "4. Select 'Mail' and 'Other (Custom name)'"
echo "   - Name it: 'Flight Bot'"
echo "   - Generate the password"
echo ""
echo "5. Copy the generated 16-character password"
echo ""
echo "6. Update your environment variables with:"
echo "   SMTP_USER=martin.navarro.dev@gmail.com"
echo "   SMTP_PASS=your-16-character-app-password"
echo ""
echo "7. In Vercel Dashboard, add these environment variables:"
echo "   - SMTP_HOST=smtp.gmail.com"
echo "   - SMTP_PORT=587"
echo "   - SMTP_USER=martin.navarro.dev@gmail.com"
echo "   - SMTP_PASS=your-16-character-app-password"
echo "   - ADMIN_EMAIL=martin.navarro.dev@gmail.com"
echo ""
echo "This will enable:"
echo "✅ User registration confirmations"
echo "✅ Alert creation notifications"
echo "✅ Price alert emails"
echo "✅ System error notifications"
echo ""
echo "Note: Email notifications are optional. The bot will work without them."
